# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Singapore Accreditation Council
title-abbreviated: SAC
description: >- # this means to ignore newlines until "baseurl:"
  Your Trusted Partner in Accreditation. Managed by Enterprise Singapore, SAC maintains the integrity and impartiality of conformity assessment practices. 
  The Council builds global trust in Singapore's products and services by strengthening our country's technical infrastructure for conformity assessments, 
  as well as forging Mutual Recognition Arrangements (MRAs) with our economic partners.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sac-accreditation.gov.sg" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-target-blank

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

collections:
  about:
    output: true
  industries:
    output: true
  services:
    output: true
  resources:
    output: true
  accredited-org:
    output: true
  courses:
    output: true

# Resource Room and Pagination
resources_name: "newsroom"
paginate: 12
paginate_path: "/newsroom/page:num"

# Homepage sections
homepage_hero_i_want_to: false # if i_want_to is true, there will be no key highlights
homepage_programmes: false
homepage_resources: true
homepage_careers: false

# Feedback Form URL
feedback_form_url: "https://form.sg/#!/forms/govtech/5a9ce876b3a3b6006e6b8335"

# FAQ URL
faq_url: "/resources/faq"
faq_url_external: false

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"

exclude:
   - node_modules
   - vendor/bundle/
   - vendor/cache/
