- year: 2019
  annual-quarter:
    - quarter: 1
      course-list:
        - title: Laboratory Management Course
          date: 4-6 March 2019
          link: /services/training/training-courses-2019/laboratory-management-course
        - title: Internal Audit Course
          date: 7-8 March 2019
          link: /services/training/training-courses-2019/internal-audit-course 
    - quarter: 2
      course-list:   
        - title: 2019 Joint courses between HSA-SAC
          date: April, May, July and August 2019
          link: /services/training/training-courses-2019/joint-courses-between-HSA-SAC
        - title: Training course on ISO/TS 22003:2013 and ISO 22000:2018
          date: 24-25 June 2019
          link: /services/training/training-courses-2019/training-course-on-isots-220032013-and-iso-220002018
        - title: Training course on ISO/IEC 17021-1:2015, ISO/IEC 17021-2:2016, ISO/IEC 17021-3:2017, ISO/IEC 17021-10:2018
          date: 17 Jun (pm) to 18 Jun 2019
          link: /services/training/training-courses-2019/training-course-ISOIEC-17021-12015,-ISOIEC-17021-22016         
    - quarter: 3
      course-list: 
    - quarter: 4
      course-list: 
- year: 2018
  annual-quarter:
    - quarter: 1
      course-list:
        - title: Laboratory Management Course
          date: 4-6 March 2019
          link: /services/training/training-courses-2019/laboratory-management-course
        - title: Internal Audit Course
          date: 7-8 March 2019
          link: /services/training/training-courses-2019/internal-audit-course 
    - quarter: 2
      course-list:   
        - title: 2019 Joint courses between HSA-SAC
          date: April, May, July and August 2019
          link: /services/training/training-courses-2019/joint-courses-between-HSA-SAC
        - title: Training course on ISO/TS 22003:2013 and ISO 22000:2018
          date: 24-25 June 2019
          link: /services/training/training-courses-2019/training-course-on-isots-220032013-and-iso-220002018
        - title: Training course on ISO/IEC 17021-1:2015, ISO/IEC 17021-2:2016, ISO/IEC 17021-3:2017, ISO/IEC 17021-10:2018
          date: 17 Jun (pm) to 18 Jun 2019
          link: /services/training/training-courses-2019/training-course-ISOIEC-17021-12015,-ISOIEC-17021-22016         
    - quarter: 3
      course-list: 
    - quarter: 4
      course-list: 
- year: 2017
  annual-quarter:
    - quarter: 1
      course-list:
        - title: Laboratory Management Course
          date: 4-6 March 2019
          link: /services/training/training-courses-2019/laboratory-management-course
        - title: Internal Audit Course
          date: 7-8 March 2019
          link: /services/training/training-courses-2019/internal-audit-course 
    - quarter: 2
      course-list:   
        - title: 2019 Joint courses between HSA-SAC
          date: April, May, July and August 2019
          link: /services/training/training-courses-2019/joint-courses-between-HSA-SAC
        - title: Training course on ISO/TS 22003:2013 and ISO 22000:2018
          date: 24-25 June 2019
          link: /services/training/training-courses-2019/training-course-on-isots-220032013-and-iso-220002018
        - title: Training course on ISO/IEC 17021-1:2015, ISO/IEC 17021-2:2016, ISO/IEC 17021-3:2017, ISO/IEC 17021-10:2018
          date: 17 Jun (pm) to 18 Jun 2019
          link: /services/training/training-courses-2019/training-course-ISOIEC-17021-12015,-ISOIEC-17021-22016         
    - quarter: 3
      course-list: 
    - quarter: 4
      course-list:       
